
services:
  api_gateway:
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile 
    restart: always
    container_name: "api_gateway"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BLOG_SERVICE_ADDRESS=blog_server:8082 
      - STAKEHOLDERS_SERVICE_ADDRESS=stakeholders-server:8081
      - TOUR_SERVICE_ADDRESS=tour-server:9090
      - JWT_SECRET_KEY=tvoja-super-tajna-rec 
    depends_on:
      - blog_server
      - stakeholders_server
      - tour_server

  stakeholders_server:
    build:
      context: . 
      dockerfile: ./Stakeholders/Dockerfile
    restart: always
    container_name: "stakeholders"
    hostname: "stakeholders-server"
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URI=mongodb://root:pass@mongo:27017
      - MONGO_DB_NAME=stakeholders_db
      - MONGO_COLLECTION_NAME=stakeholders
    depends_on:
      mongo:
        condition: service_healthy

  blog_server:
    build:
      context: .
      dockerfile: ./Blog/Dockerfile
    restart: always
    container_name: "blog"
    hostname: "blog-server"
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGO_URI=mongodb://root:pass@mongo:27017
      - MONGO_DB_NAME=blog_db
      - MONGO_COLLECTION_NAME=blog
    depends_on:
      mongo:
        condition: service_healthy

  tour_server:
    build:
      context: .
      dockerfile: ./Tour/Dockerfile
    restart: always
    container_name: "tour"
    hostname: "tour-server"
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tour_db
      - DB_USER=tour_db
      - DB_PASSWORD=tour_db123
    depends_on:
      postgres:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: stakeholders_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "9200:8081"
    volumes:
      - mongo_express_data:/data/db

  postgres:
    image: postgres:15
    container_name: "postgres"
    restart: always
    ports:
      - "9201:5432"
    environment:
      POSTGRES_DB: tour_db
      POSTGRES_USER: tour_db
      POSTGRES_PASSWORD: tour_db123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tour_db"]
      interval: 10s
      retries: 5

volumes:
  mongo_store:
  mongo_express_data:
  postgres_data: