services:
  api_gateway:
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile 
    restart: always
    container_name: "api_gateway"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BLOG_SERVICE_ADDRESS=blog_server:8082 
      - STAKEHOLDERS_SERVICE_ADDRESS=stakeholders-server:8081
      - TOUR_SERVICE_ADDRESS=tour-server:9090
      - FOLLOWER_SERVICE_ADDRESS=follower_server:8084 # Dodato
      - JWT_SECRET_KEY=tvoja-super-tajna-rec 
    volumes:
      - ./api_gateway_uploads:/uploads
    depends_on:
      - blog_server
      - stakeholders_server
      - tour_server
      - follower_server 

  stakeholders_server:
    build:
      context: . 
      dockerfile: ./Stakeholders/Dockerfile
    restart: always
    container_name: "stakeholders"
    hostname: "stakeholders-server"
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URI=mongodb://root:pass@mongo:27017
      - MONGO_DB_NAME=stakeholders_db
      - MONGO_COLLECTION_NAME=stakeholders
      - NATS_URI=nats://nats-server:4222
    depends_on:
      mongo:
        condition: service_healthy
      nats-server:
        condition: service_healthy

  blog_server:
    build:
      context: .
      dockerfile: ./Blog/Dockerfile
    restart: always
    container_name: "blog"
    hostname: "blog-server"
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGO_URI=mongodb://root:pass@mongo:27017
      - MONGO_DB_NAME=blog_db
      - MONGO_COLLECTION_NAME=blog
      - NATS_URI=nats://nats-server:4222
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      mongo:
        condition: service_healthy
      nats-server:
        condition: service_healthy

  tour_server:
    build:
      context: .
      dockerfile: ./Tour/Dockerfile
    restart: always
    container_name: "tour"
    hostname: "tour-server"
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tour_db
      - DB_USER=tour_db
      - DB_PASSWORD=tour_db123
    depends_on:
      postgres:
        condition: service_healthy

  follower_server:
    build:
      context: .
      dockerfile: ./Follower/Dockerfile
    restart: always
    container_name: "follower"
    hostname: "follower-server"
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - NEO4J_URI=bolt://neo4j:7687 # Adresa Neo4j Bolt protokola
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=neo4j_password 
    depends_on:
      neo4j: 
        condition: service_healthy
  nats-server:
    build:
      context: .
      dockerfile: ./saga/Dockerfile # <--- KLJUČNA IZMENA 1: Koristimo build
    container_name: nats    # <--- Vraćamo ime servisa na nats-server i u container_name
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: 
      - "-js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222"]
      interval: 10s
      timeout: 5s
      retries: 5   
        
  neo4j:
    image: neo4j:5
    container_name: "neo4j"
    restart: always
    ports:
      - "7474:7474"     # Neo4j Browser (GUI)
      - "7687:7687"     # Bolt protokol
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_dbms_security_auth__enabled=true
      # (opciono) uključi APOC core:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j_password", "RETURN 1;"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - neo4j_data:/data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: stakeholders_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "9200:8081"
    volumes:
      - mongo_express_data:/data/db

  postgres:
    image: postgres:15
    container_name: "postgres"
    restart: always
    ports:
      - "9201:5432"
    environment:
      POSTGRES_DB: tour_db
      POSTGRES_USER: tour_db
      POSTGRES_PASSWORD: tour_db123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tour_db"]
      interval: 10s
      retries: 5

volumes:
  mongo_store:
  mongo_express_data:
  postgres_data:
  neo4j_data: 
  neo4j_plugins: 
