spring.application.name=Tour


# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/tour_db
spring.datasource.username=tour_db
spring.datasource.password=tour_db123
spring.datasource.driver-class-name=org.postgresql.Driver


spring.profiles.active=default

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#OVO DOLE JE LAKIJEV DEO ZA LOKAL       

spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.platform=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/soa

spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true


spring.datasource.initialization-mode=always


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8083
grpc.server.port=9090

