FROM golang:alpine as build_container
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o stakeholders

FROM alpine
COPY --from=build_container /app/stakeholders /usr/bin
EXPOSE 8081
ENTRYPOINT ["stakeholders"]