// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: keypoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyPointGrpcService_CreateKeyPoint_FullMethodName      = "/tour.KeyPointGrpcService/CreateKeyPoint"
	KeyPointGrpcService_GetKeyPointsForTour_FullMethodName = "/tour.KeyPointGrpcService/GetKeyPointsForTour"
	KeyPointGrpcService_UpdateKeyPoint_FullMethodName      = "/tour.KeyPointGrpcService/UpdateKeyPoint"
	KeyPointGrpcService_DeleteKeyPoint_FullMethodName      = "/tour.KeyPointGrpcService/DeleteKeyPoint"
)

// KeyPointGrpcServiceClient is the client API for KeyPointGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyPointGrpcServiceClient interface {
	CreateKeyPoint(ctx context.Context, in *CreateKeyPointRequest, opts ...grpc.CallOption) (*CreateKeyPointResponse, error)
	GetKeyPointsForTour(ctx context.Context, in *GetKeyPointsForTourRequest, opts ...grpc.CallOption) (*GetKeyPointsForTourResponse, error)
	UpdateKeyPoint(ctx context.Context, in *UpdateKeyPointRequest, opts ...grpc.CallOption) (*UpdateKeyPointResponse, error)
	DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error)
}

type keyPointGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyPointGrpcServiceClient(cc grpc.ClientConnInterface) KeyPointGrpcServiceClient {
	return &keyPointGrpcServiceClient{cc}
}

func (c *keyPointGrpcServiceClient) CreateKeyPoint(ctx context.Context, in *CreateKeyPointRequest, opts ...grpc.CallOption) (*CreateKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyPointResponse)
	err := c.cc.Invoke(ctx, KeyPointGrpcService_CreateKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointGrpcServiceClient) GetKeyPointsForTour(ctx context.Context, in *GetKeyPointsForTourRequest, opts ...grpc.CallOption) (*GetKeyPointsForTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPointsForTourResponse)
	err := c.cc.Invoke(ctx, KeyPointGrpcService_GetKeyPointsForTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointGrpcServiceClient) UpdateKeyPoint(ctx context.Context, in *UpdateKeyPointRequest, opts ...grpc.CallOption) (*UpdateKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKeyPointResponse)
	err := c.cc.Invoke(ctx, KeyPointGrpcService_UpdateKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointGrpcServiceClient) DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyPointResponse)
	err := c.cc.Invoke(ctx, KeyPointGrpcService_DeleteKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyPointGrpcServiceServer is the server API for KeyPointGrpcService service.
// All implementations must embed UnimplementedKeyPointGrpcServiceServer
// for forward compatibility.
type KeyPointGrpcServiceServer interface {
	CreateKeyPoint(context.Context, *CreateKeyPointRequest) (*CreateKeyPointResponse, error)
	GetKeyPointsForTour(context.Context, *GetKeyPointsForTourRequest) (*GetKeyPointsForTourResponse, error)
	UpdateKeyPoint(context.Context, *UpdateKeyPointRequest) (*UpdateKeyPointResponse, error)
	DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error)
	mustEmbedUnimplementedKeyPointGrpcServiceServer()
}

// UnimplementedKeyPointGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyPointGrpcServiceServer struct{}

func (UnimplementedKeyPointGrpcServiceServer) CreateKeyPoint(context.Context, *CreateKeyPointRequest) (*CreateKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyPoint not implemented")
}
func (UnimplementedKeyPointGrpcServiceServer) GetKeyPointsForTour(context.Context, *GetKeyPointsForTourRequest) (*GetKeyPointsForTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointsForTour not implemented")
}
func (UnimplementedKeyPointGrpcServiceServer) UpdateKeyPoint(context.Context, *UpdateKeyPointRequest) (*UpdateKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyPoint not implemented")
}
func (UnimplementedKeyPointGrpcServiceServer) DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyPoint not implemented")
}
func (UnimplementedKeyPointGrpcServiceServer) mustEmbedUnimplementedKeyPointGrpcServiceServer() {}
func (UnimplementedKeyPointGrpcServiceServer) testEmbeddedByValue()                             {}

// UnsafeKeyPointGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyPointGrpcServiceServer will
// result in compilation errors.
type UnsafeKeyPointGrpcServiceServer interface {
	mustEmbedUnimplementedKeyPointGrpcServiceServer()
}

func RegisterKeyPointGrpcServiceServer(s grpc.ServiceRegistrar, srv KeyPointGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyPointGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyPointGrpcService_ServiceDesc, srv)
}

func _KeyPointGrpcService_CreateKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointGrpcServiceServer).CreateKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointGrpcService_CreateKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointGrpcServiceServer).CreateKeyPoint(ctx, req.(*CreateKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointGrpcService_GetKeyPointsForTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointsForTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointGrpcServiceServer).GetKeyPointsForTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointGrpcService_GetKeyPointsForTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointGrpcServiceServer).GetKeyPointsForTour(ctx, req.(*GetKeyPointsForTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointGrpcService_UpdateKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointGrpcServiceServer).UpdateKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointGrpcService_UpdateKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointGrpcServiceServer).UpdateKeyPoint(ctx, req.(*UpdateKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointGrpcService_DeleteKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointGrpcServiceServer).DeleteKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointGrpcService_DeleteKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointGrpcServiceServer).DeleteKeyPoint(ctx, req.(*DeleteKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyPointGrpcService_ServiceDesc is the grpc.ServiceDesc for KeyPointGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyPointGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.KeyPointGrpcService",
	HandlerType: (*KeyPointGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKeyPoint",
			Handler:    _KeyPointGrpcService_CreateKeyPoint_Handler,
		},
		{
			MethodName: "GetKeyPointsForTour",
			Handler:    _KeyPointGrpcService_GetKeyPointsForTour_Handler,
		},
		{
			MethodName: "UpdateKeyPoint",
			Handler:    _KeyPointGrpcService_UpdateKeyPoint_Handler,
		},
		{
			MethodName: "DeleteKeyPoint",
			Handler:    _KeyPointGrpcService_DeleteKeyPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keypoint.proto",
}
