// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: review.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewGrpcService_CreateReview_FullMethodName      = "/tour.ReviewGrpcService/CreateReview"
	ReviewGrpcService_GetReviewsForTour_FullMethodName = "/tour.ReviewGrpcService/GetReviewsForTour"
)

// ReviewGrpcServiceClient is the client API for ReviewGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewGrpcServiceClient interface {
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
	GetReviewsForTour(ctx context.Context, in *GetReviewForTourRequest, opts ...grpc.CallOption) (*ReviewsResponse, error)
}

type reviewGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewGrpcServiceClient(cc grpc.ClientConnInterface) ReviewGrpcServiceClient {
	return &reviewGrpcServiceClient{cc}
}

func (c *reviewGrpcServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, ReviewGrpcService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewGrpcServiceClient) GetReviewsForTour(ctx context.Context, in *GetReviewForTourRequest, opts ...grpc.CallOption) (*ReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewsResponse)
	err := c.cc.Invoke(ctx, ReviewGrpcService_GetReviewsForTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewGrpcServiceServer is the server API for ReviewGrpcService service.
// All implementations must embed UnimplementedReviewGrpcServiceServer
// for forward compatibility.
type ReviewGrpcServiceServer interface {
	CreateReview(context.Context, *CreateReviewRequest) (*ReviewResponse, error)
	GetReviewsForTour(context.Context, *GetReviewForTourRequest) (*ReviewsResponse, error)
	mustEmbedUnimplementedReviewGrpcServiceServer()
}

// UnimplementedReviewGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewGrpcServiceServer struct{}

func (UnimplementedReviewGrpcServiceServer) CreateReview(context.Context, *CreateReviewRequest) (*ReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedReviewGrpcServiceServer) GetReviewsForTour(context.Context, *GetReviewForTourRequest) (*ReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewsForTour not implemented")
}
func (UnimplementedReviewGrpcServiceServer) mustEmbedUnimplementedReviewGrpcServiceServer() {}
func (UnimplementedReviewGrpcServiceServer) testEmbeddedByValue()                           {}

// UnsafeReviewGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewGrpcServiceServer will
// result in compilation errors.
type UnsafeReviewGrpcServiceServer interface {
	mustEmbedUnimplementedReviewGrpcServiceServer()
}

func RegisterReviewGrpcServiceServer(s grpc.ServiceRegistrar, srv ReviewGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedReviewGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewGrpcService_ServiceDesc, srv)
}

func _ReviewGrpcService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewGrpcServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewGrpcService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewGrpcServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewGrpcService_GetReviewsForTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewForTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewGrpcServiceServer).GetReviewsForTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewGrpcService_GetReviewsForTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewGrpcServiceServer).GetReviewsForTour(ctx, req.(*GetReviewForTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewGrpcService_ServiceDesc is the grpc.ServiceDesc for ReviewGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.ReviewGrpcService",
	HandlerType: (*ReviewGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReview",
			Handler:    _ReviewGrpcService_CreateReview_Handler,
		},
		{
			MethodName: "GetReviewsForTour",
			Handler:    _ReviewGrpcService_GetReviewsForTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}
