// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: review.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	TouristId     string                 `protobuf:"bytes,4,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	VisitDate     string                 `protobuf:"bytes,5,opt,name=visitDate,proto3" json:"visitDate,omitempty"`
	CreatedDate   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	Images        []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	TourId        int32                  `protobuf:"varint,8,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *Review) GetVisitDate() string {
	if x != nil {
		return x.VisitDate
	}
	return ""
}

func (x *Review) GetCreatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

func (x *Review) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Review) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        int32                  `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	TouristId     string                 `protobuf:"bytes,3,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	VisitDate     string                 `protobuf:"bytes,4,opt,name=visitDate,proto3" json:"visitDate,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	TourId        int32                  `protobuf:"varint,6,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateReviewRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *CreateReviewRequest) GetVisitDate() string {
	if x != nil {
		return x.VisitDate
	}
	return ""
}

func (x *CreateReviewRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateReviewRequest) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type GetReviewForTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int32                  `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewForTourRequest) Reset() {
	*x = GetReviewForTourRequest{}
	mi := &file_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewForTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewForTourRequest) ProtoMessage() {}

func (x *GetReviewForTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewForTourRequest.ProtoReflect.Descriptor instead.
func (*GetReviewForTourRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{2}
}

func (x *GetReviewForTourRequest) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type ReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewsResponse) Reset() {
	*x = ReviewsResponse{}
	mi := &file_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewsResponse) ProtoMessage() {}

func (x *ReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewsResponse.ProtoReflect.Descriptor instead.
func (*ReviewsResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_review_proto protoreflect.FileDescriptor

const file_review_proto_rawDesc = "" +
	"\n" +
	"\freview.proto\x12\x04tour\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x04 \x01(\tR\ttouristId\x12\x1c\n" +
	"\tvisitDate\x18\x05 \x01(\tR\tvisitDate\x12<\n" +
	"\vcreatedDate\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedDate\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12\x17\n" +
	"\atour_id\x18\b \x01(\x05R\x06tourId\"\xb5\x01\n" +
	"\x13CreateReviewRequest\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x03 \x01(\tR\ttouristId\x12\x1c\n" +
	"\tvisitDate\x18\x04 \x01(\tR\tvisitDate\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12\x17\n" +
	"\atour_id\x18\x06 \x01(\x05R\x06tourId\"2\n" +
	"\x17GetReviewForTourRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\x05R\x06tourId\"6\n" +
	"\x0eReviewResponse\x12$\n" +
	"\x06review\x18\x01 \x01(\v2\f.tour.ReviewR\x06review\"9\n" +
	"\x0fReviewsResponse\x12&\n" +
	"\areviews\x18\x01 \x03(\v2\f.tour.ReviewR\areviews2\x9f\x01\n" +
	"\x11ReviewGrpcService\x12?\n" +
	"\fCreateReview\x12\x19.tour.CreateReviewRequest\x1a\x14.tour.ReviewResponse\x12I\n" +
	"\x11GetReviewsForTour\x12\x1d.tour.GetReviewForTourRequest\x1a\x15.tour.ReviewsResponseBe\n" +
	"\x15com.example.tour.grpcB\vReviewProtoP\x01Z=github.com/pavlovicisidora/soa-team7/Backend/APIGateway/protob\x06proto3"

var (
	file_review_proto_rawDescOnce sync.Once
	file_review_proto_rawDescData []byte
)

func file_review_proto_rawDescGZIP() []byte {
	file_review_proto_rawDescOnce.Do(func() {
		file_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)))
	})
	return file_review_proto_rawDescData
}

var file_review_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_review_proto_goTypes = []any{
	(*Review)(nil),                  // 0: tour.Review
	(*CreateReviewRequest)(nil),     // 1: tour.CreateReviewRequest
	(*GetReviewForTourRequest)(nil), // 2: tour.GetReviewForTourRequest
	(*ReviewResponse)(nil),          // 3: tour.ReviewResponse
	(*ReviewsResponse)(nil),         // 4: tour.ReviewsResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_review_proto_depIdxs = []int32{
	5, // 0: tour.Review.createdDate:type_name -> google.protobuf.Timestamp
	0, // 1: tour.ReviewResponse.review:type_name -> tour.Review
	0, // 2: tour.ReviewsResponse.reviews:type_name -> tour.Review
	1, // 3: tour.ReviewGrpcService.CreateReview:input_type -> tour.CreateReviewRequest
	2, // 4: tour.ReviewGrpcService.GetReviewsForTour:input_type -> tour.GetReviewForTourRequest
	3, // 5: tour.ReviewGrpcService.CreateReview:output_type -> tour.ReviewResponse
	4, // 6: tour.ReviewGrpcService.GetReviewsForTour:output_type -> tour.ReviewsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_review_proto_init() }
func file_review_proto_init() {
	if File_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_goTypes,
		DependencyIndexes: file_review_proto_depIdxs,
		MessageInfos:      file_review_proto_msgTypes,
	}.Build()
	File_review_proto = out.File
	file_review_proto_goTypes = nil
	file_review_proto_depIdxs = nil
}
