// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/tour.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourGrpcService_CreateTour_FullMethodName      = "/tour.TourGrpcService/CreateTour"
	TourGrpcService_GetAllToursById_FullMethodName = "/tour.TourGrpcService/GetAllToursById"
	TourGrpcService_GetAllTours_FullMethodName     = "/tour.TourGrpcService/GetAllTours"
	TourGrpcService_GetTourById_FullMethodName     = "/tour.TourGrpcService/GetTourById"
	TourGrpcService_StartTour_FullMethodName       = "/tour.TourGrpcService/StartTour"
	TourGrpcService_AbandonTour_FullMethodName     = "/tour.TourGrpcService/AbandonTour"
	TourGrpcService_CompleteTour_FullMethodName    = "/tour.TourGrpcService/CompleteTour"
)

// TourGrpcServiceClient is the client API for TourGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourGrpcServiceClient interface {
	CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*CreateTourResponse, error)
	GetAllToursById(ctx context.Context, in *GetAllToursByIdRequest, opts ...grpc.CallOption) (*GetAllToursByIdResponse, error)
	GetAllTours(ctx context.Context, in *GetAllToursRequest, opts ...grpc.CallOption) (*GetAllToursResponse, error)
	GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*GetTourByIdResponse, error)
	StartTour(ctx context.Context, in *StartTourRequest, opts ...grpc.CallOption) (*StartTourResponse, error)
	AbandonTour(ctx context.Context, in *AbandonTourRequest, opts ...grpc.CallOption) (*AbandonTourResponse, error)
	CompleteTour(ctx context.Context, in *CompleteTourRequest, opts ...grpc.CallOption) (*CompleteTourResponse, error)
}

type tourGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourGrpcServiceClient(cc grpc.ClientConnInterface) TourGrpcServiceClient {
	return &tourGrpcServiceClient{cc}
}

func (c *tourGrpcServiceClient) CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*CreateTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTourResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_CreateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourGrpcServiceClient) GetAllToursById(ctx context.Context, in *GetAllToursByIdRequest, opts ...grpc.CallOption) (*GetAllToursByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllToursByIdResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_GetAllToursById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourGrpcServiceClient) GetAllTours(ctx context.Context, in *GetAllToursRequest, opts ...grpc.CallOption) (*GetAllToursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllToursResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_GetAllTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourGrpcServiceClient) GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*GetTourByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTourByIdResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_GetTourById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourGrpcServiceClient) StartTour(ctx context.Context, in *StartTourRequest, opts ...grpc.CallOption) (*StartTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTourResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_StartTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourGrpcServiceClient) AbandonTour(ctx context.Context, in *AbandonTourRequest, opts ...grpc.CallOption) (*AbandonTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonTourResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_AbandonTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourGrpcServiceClient) CompleteTour(ctx context.Context, in *CompleteTourRequest, opts ...grpc.CallOption) (*CompleteTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTourResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_CompleteTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourGrpcServiceServer is the server API for TourGrpcService service.
// All implementations must embed UnimplementedTourGrpcServiceServer
// for forward compatibility.
type TourGrpcServiceServer interface {
	CreateTour(context.Context, *CreateTourRequest) (*CreateTourResponse, error)
	GetAllToursById(context.Context, *GetAllToursByIdRequest) (*GetAllToursByIdResponse, error)
	GetAllTours(context.Context, *GetAllToursRequest) (*GetAllToursResponse, error)
	GetTourById(context.Context, *GetTourByIdRequest) (*GetTourByIdResponse, error)
	StartTour(context.Context, *StartTourRequest) (*StartTourResponse, error)
	AbandonTour(context.Context, *AbandonTourRequest) (*AbandonTourResponse, error)
	CompleteTour(context.Context, *CompleteTourRequest) (*CompleteTourResponse, error)
	mustEmbedUnimplementedTourGrpcServiceServer()
}

// UnimplementedTourGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourGrpcServiceServer struct{}

func (UnimplementedTourGrpcServiceServer) CreateTour(context.Context, *CreateTourRequest) (*CreateTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourGrpcServiceServer) GetAllToursById(context.Context, *GetAllToursByIdRequest) (*GetAllToursByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllToursById not implemented")
}
func (UnimplementedTourGrpcServiceServer) GetAllTours(context.Context, *GetAllToursRequest) (*GetAllToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTours not implemented")
}
func (UnimplementedTourGrpcServiceServer) GetTourById(context.Context, *GetTourByIdRequest) (*GetTourByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedTourGrpcServiceServer) StartTour(context.Context, *StartTourRequest) (*StartTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTour not implemented")
}
func (UnimplementedTourGrpcServiceServer) AbandonTour(context.Context, *AbandonTourRequest) (*AbandonTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonTour not implemented")
}
func (UnimplementedTourGrpcServiceServer) CompleteTour(context.Context, *CompleteTourRequest) (*CompleteTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTour not implemented")
}
func (UnimplementedTourGrpcServiceServer) mustEmbedUnimplementedTourGrpcServiceServer() {}
func (UnimplementedTourGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeTourGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourGrpcServiceServer will
// result in compilation errors.
type UnsafeTourGrpcServiceServer interface {
	mustEmbedUnimplementedTourGrpcServiceServer()
}

func RegisterTourGrpcServiceServer(s grpc.ServiceRegistrar, srv TourGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedTourGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourGrpcService_ServiceDesc, srv)
}

func _TourGrpcService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_CreateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).CreateTour(ctx, req.(*CreateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourGrpcService_GetAllToursById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllToursByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).GetAllToursById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_GetAllToursById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).GetAllToursById(ctx, req.(*GetAllToursByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourGrpcService_GetAllTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).GetAllTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_GetAllTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).GetAllTours(ctx, req.(*GetAllToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourGrpcService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_GetTourById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).GetTourById(ctx, req.(*GetTourByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourGrpcService_StartTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).StartTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_StartTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).StartTour(ctx, req.(*StartTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourGrpcService_AbandonTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).AbandonTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_AbandonTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).AbandonTour(ctx, req.(*AbandonTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourGrpcService_CompleteTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).CompleteTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_CompleteTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).CompleteTour(ctx, req.(*CompleteTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourGrpcService_ServiceDesc is the grpc.ServiceDesc for TourGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourGrpcService",
	HandlerType: (*TourGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTour",
			Handler:    _TourGrpcService_CreateTour_Handler,
		},
		{
			MethodName: "GetAllToursById",
			Handler:    _TourGrpcService_GetAllToursById_Handler,
		},
		{
			MethodName: "GetAllTours",
			Handler:    _TourGrpcService_GetAllTours_Handler,
		},
		{
			MethodName: "GetTourById",
			Handler:    _TourGrpcService_GetTourById_Handler,
		},
		{
			MethodName: "StartTour",
			Handler:    _TourGrpcService_StartTour_Handler,
		},
		{
			MethodName: "AbandonTour",
			Handler:    _TourGrpcService_AbandonTour_Handler,
		},
		{
			MethodName: "CompleteTour",
			Handler:    _TourGrpcService_CompleteTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour.proto",
}
