// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.0
// source: tour.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourStatus int32

const (
	TourStatus_DRAFT     TourStatus = 0
	TourStatus_PUBLISHED TourStatus = 1
	TourStatus_ARCHIVED  TourStatus = 2
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "ARCHIVED",
	}
	TourStatus_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"ARCHIVED":  2,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tour_proto_enumTypes[0].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_tour_proto_enumTypes[0]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{0}
}

type Tour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty        string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags              []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price             float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId          string                 `protobuf:"bytes,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	DistanceInKm      float64                `protobuf:"fixed64,9,opt,name=distance_in_km,json=distanceInKm,proto3" json:"distance_in_km,omitempty"`
	PublishedDateTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_date_time,json=publishedDateTime,proto3" json:"published_date_time,omitempty"`
	ArchivedDateTime  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=archived_date_time,json=archivedDateTime,proto3" json:"archived_date_time,omitempty"`
}

func (x *Tour) Reset() {
	*x = Tour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tour) GetDistanceInKm() float64 {
	if x != nil {
		return x.DistanceInKm
	}
	return 0
}

func (x *Tour) GetPublishedDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedDateTime
	}
	return nil
}

func (x *Tour) GetArchivedDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedDateTime
	}
	return nil
}

type CreateTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty  string   `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags        []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId    string   `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CreateTourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tour *Tour `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
}

func (x *CreateTourResponse) Reset() {
	*x = CreateTourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourResponse) ProtoMessage() {}

func (x *CreateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourResponse.ProtoReflect.Descriptor instead.
func (*CreateTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type GetAllToursByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId string `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *GetAllToursByIdRequest) Reset() {
	*x = GetAllToursByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllToursByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursByIdRequest) ProtoMessage() {}

func (x *GetAllToursByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAllToursByIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllToursByIdRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type GetAllToursByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tours []*Tour `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
}

func (x *GetAllToursByIdResponse) Reset() {
	*x = GetAllToursByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllToursByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursByIdResponse) ProtoMessage() {}

func (x *GetAllToursByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursByIdResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllToursByIdResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetAllToursRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllToursRequest) Reset() {
	*x = GetAllToursRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursRequest) ProtoMessage() {}

func (x *GetAllToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursRequest.ProtoReflect.Descriptor instead.
func (*GetAllToursRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{5}
}

type GetAllToursResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tours []*Tour `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
}

func (x *GetAllToursResponse) Reset() {
	*x = GetAllToursResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursResponse) ProtoMessage() {}

func (x *GetAllToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllToursResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId int32 `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{7}
}

func (x *GetTourByIdRequest) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type GetTourByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tour *Tour `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
}

func (x *GetTourByIdResponse) Reset() {
	*x = GetTourByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdResponse) ProtoMessage() {}

func (x *GetTourByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTourByIdResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{8}
}

func (x *GetTourByIdResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type UpdateTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tour *Tour `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
}

func (x *UpdateTourRequest) Reset() {
	*x = UpdateTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourRequest) ProtoMessage() {}

func (x *UpdateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTourRequest) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type UpdateTourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tour *Tour `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
}

func (x *UpdateTourResponse) Reset() {
	*x = UpdateTourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourResponse) ProtoMessage() {}

func (x *UpdateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourResponse.ProtoReflect.Descriptor instead.
func (*UpdateTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type TourExecution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId         int32                  `protobuf:"varint,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId      string                 `protobuf:"bytes,3,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	LastActivity   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	CompletionTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"`
}

func (x *TourExecution) Reset() {
	*x = TourExecution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TourExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecution) ProtoMessage() {}

func (x *TourExecution) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecution.ProtoReflect.Descriptor instead.
func (*TourExecution) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{11}
}

func (x *TourExecution) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourExecution) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *TourExecution) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TourExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourExecution) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TourExecution) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *TourExecution) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

type StartTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId    int32   `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId string  `protobuf:"bytes,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *StartTourRequest) Reset() {
	*x = StartTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTourRequest) ProtoMessage() {}

func (x *StartTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTourRequest.ProtoReflect.Descriptor instead.
func (*StartTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{12}
}

func (x *StartTourRequest) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *StartTourRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *StartTourRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *StartTourRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type StartTourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourExecution *TourExecution `protobuf:"bytes,1,opt,name=tour_execution,json=tourExecution,proto3" json:"tour_execution,omitempty"`
}

func (x *StartTourResponse) Reset() {
	*x = StartTourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTourResponse) ProtoMessage() {}

func (x *StartTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTourResponse.ProtoReflect.Descriptor instead.
func (*StartTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{13}
}

func (x *StartTourResponse) GetTourExecution() *TourExecution {
	if x != nil {
		return x.TourExecution
	}
	return nil
}

type AbandonTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourExecutionId int32 `protobuf:"varint,1,opt,name=tour_execution_id,json=tourExecutionId,proto3" json:"tour_execution_id,omitempty"`
}

func (x *AbandonTourRequest) Reset() {
	*x = AbandonTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonTourRequest) ProtoMessage() {}

func (x *AbandonTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonTourRequest.ProtoReflect.Descriptor instead.
func (*AbandonTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{14}
}

func (x *AbandonTourRequest) GetTourExecutionId() int32 {
	if x != nil {
		return x.TourExecutionId
	}
	return 0
}

type AbandonTourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourExecution *TourExecution `protobuf:"bytes,1,opt,name=tour_execution,json=tourExecution,proto3" json:"tour_execution,omitempty"`
}

func (x *AbandonTourResponse) Reset() {
	*x = AbandonTourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonTourResponse) ProtoMessage() {}

func (x *AbandonTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonTourResponse.ProtoReflect.Descriptor instead.
func (*AbandonTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{15}
}

func (x *AbandonTourResponse) GetTourExecution() *TourExecution {
	if x != nil {
		return x.TourExecution
	}
	return nil
}

type CompleteTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourExecutionId int32 `protobuf:"varint,1,opt,name=tour_execution_id,json=tourExecutionId,proto3" json:"tour_execution_id,omitempty"`
}

func (x *CompleteTourRequest) Reset() {
	*x = CompleteTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTourRequest) ProtoMessage() {}

func (x *CompleteTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTourRequest.ProtoReflect.Descriptor instead.
func (*CompleteTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{16}
}

func (x *CompleteTourRequest) GetTourExecutionId() int32 {
	if x != nil {
		return x.TourExecutionId
	}
	return 0
}

type CompleteTourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourExecution *TourExecution `protobuf:"bytes,1,opt,name=tour_execution,json=tourExecution,proto3" json:"tour_execution,omitempty"`
}

func (x *CompleteTourResponse) Reset() {
	*x = CompleteTourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTourResponse) ProtoMessage() {}

func (x *CompleteTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTourResponse.ProtoReflect.Descriptor instead.
func (*CompleteTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{17}
}

func (x *CompleteTourResponse) GetTourExecution() *TourExecution {
	if x != nil {
		return x.TourExecution
	}
	return nil
}

type GetTourExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourExecutionId int32 `protobuf:"varint,1,opt,name=tour_execution_id,json=tourExecutionId,proto3" json:"tour_execution_id,omitempty"`
}

func (x *GetTourExecutionRequest) Reset() {
	*x = GetTourExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourExecutionRequest) ProtoMessage() {}

func (x *GetTourExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetTourExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{18}
}

func (x *GetTourExecutionRequest) GetTourExecutionId() int32 {
	if x != nil {
		return x.TourExecutionId
	}
	return 0
}

type GetTourExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourExecution *TourExecution `protobuf:"bytes,1,opt,name=tour_execution,json=tourExecution,proto3" json:"tour_execution,omitempty"`
	Tour          *Tour          `protobuf:"bytes,2,opt,name=tour,proto3" json:"tour,omitempty"`
}

func (x *GetTourExecutionResponse) Reset() {
	*x = GetTourExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourExecutionResponse) ProtoMessage() {}

func (x *GetTourExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourExecutionResponse.ProtoReflect.Descriptor instead.
func (*GetTourExecutionResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{19}
}

func (x *GetTourExecutionResponse) GetTourExecution() *TourExecution {
	if x != nil {
		return x.TourExecution
	}
	return nil
}

func (x *GetTourExecutionResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

var File_tour_proto protoreflect.FileDescriptor

var file_tour_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x6f,
	0x75, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x87, 0x03, 0x0a, 0x04, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x6e,
	0x5f, 0x6b, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x6e, 0x4b, 0x6d, 0x12, 0x4a, 0x0a, 0x13, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x11, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x12, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x9a, 0x01,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x04, 0x74, 0x6f, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x04, 0x74, 0x6f, 0x75, 0x72,
	0x22, 0x35, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x05, 0x74,
	0x6f, 0x75, 0x72, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f,
	0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x05, 0x74, 0x6f,
	0x75, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x75,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72,
	0x49, 0x64, 0x22, 0x35, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x6f, 0x75,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54,
	0x6f, 0x75, 0x72, 0x52, 0x04, 0x74, 0x6f, 0x75, 0x72, 0x22, 0x33, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x04, 0x74, 0x6f, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74,
	0x6f, 0x75, 0x72, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x04, 0x74, 0x6f, 0x75, 0x72, 0x22, 0x34,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x6f, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x04,
	0x74, 0x6f, 0x75, 0x72, 0x22, 0xb0, 0x02, 0x0a, 0x0d, 0x54, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x12, 0x43, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74,
	0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x75, 0x72, 0x69,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x4f,
	0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x6f,
	0x75, 0x72, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0d, 0x74, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x40, 0x0a, 0x12, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0f, 0x74, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x51, 0x0a, 0x13, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x54, 0x6f, 0x75, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x74, 0x6f, 0x75, 0x72,
	0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x74, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x74,
	0x6f, 0x75, 0x72, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x74, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x0e, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54,
	0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x74, 0x6f,
	0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x74, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x76, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x0e, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x54, 0x6f,
	0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x74, 0x6f, 0x75,
	0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x6f,
	0x75, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e,
	0x54, 0x6f, 0x75, 0x72, 0x52, 0x04, 0x74, 0x6f, 0x75, 0x72, 0x2a, 0x34, 0x0a, 0x0a, 0x54, 0x6f,
	0x75, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x41, 0x46,
	0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02,
	0x32, 0x87, 0x05, 0x0a, 0x0f, 0x54, 0x6f, 0x75, 0x72, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x75, 0x72, 0x12, 0x17, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f,
	0x75, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54,
	0x6f, 0x75, 0x72, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54,
	0x6f, 0x75, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x75, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75,
	0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x17, 0x2e, 0x74, 0x6f,
	0x75, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x16, 0x2e, 0x74, 0x6f,
	0x75, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b,
	0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x18, 0x2e, 0x74, 0x6f,
	0x75, 0x72, 0x2e, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x41, 0x62, 0x61,
	0x6e, 0x64, 0x6f, 0x6e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x45, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72,
	0x12, 0x19, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x6f,
	0x75, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x74, 0x6f,
	0x75, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x6f, 0x75,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x63, 0x0a, 0x15, 0x63, 0x6f,
	0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x42, 0x09, 0x54, 0x6f, 0x75, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x76,
	0x6c, 0x6f, 0x76, 0x69, 0x63, 0x69, 0x73, 0x69, 0x64, 0x6f, 0x72, 0x61, 0x2f, 0x73, 0x6f, 0x61,
	0x2d, 0x74, 0x65, 0x61, 0x6d, 0x37, 0x2f, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x41,
	0x50, 0x49, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tour_proto_rawDescOnce sync.Once
	file_tour_proto_rawDescData = file_tour_proto_rawDesc
)

func file_tour_proto_rawDescGZIP() []byte {
	file_tour_proto_rawDescOnce.Do(func() {
		file_tour_proto_rawDescData = protoimpl.X.CompressGZIP(file_tour_proto_rawDescData)
	})
	return file_tour_proto_rawDescData
}

var file_tour_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_tour_proto_goTypes = []any{
	(TourStatus)(0),                  // 0: tour.TourStatus
	(*Tour)(nil),                     // 1: tour.Tour
	(*CreateTourRequest)(nil),        // 2: tour.CreateTourRequest
	(*CreateTourResponse)(nil),       // 3: tour.CreateTourResponse
	(*GetAllToursByIdRequest)(nil),   // 4: tour.GetAllToursByIdRequest
	(*GetAllToursByIdResponse)(nil),  // 5: tour.GetAllToursByIdResponse
	(*GetAllToursRequest)(nil),       // 6: tour.GetAllToursRequest
	(*GetAllToursResponse)(nil),      // 7: tour.GetAllToursResponse
	(*GetTourByIdRequest)(nil),       // 8: tour.GetTourByIdRequest
	(*GetTourByIdResponse)(nil),      // 9: tour.GetTourByIdResponse
	(*UpdateTourRequest)(nil),        // 10: tour.UpdateTourRequest
	(*UpdateTourResponse)(nil),       // 11: tour.UpdateTourResponse
	(*TourExecution)(nil),            // 12: tour.TourExecution
	(*StartTourRequest)(nil),         // 13: tour.StartTourRequest
	(*StartTourResponse)(nil),        // 14: tour.StartTourResponse
	(*AbandonTourRequest)(nil),       // 15: tour.AbandonTourRequest
	(*AbandonTourResponse)(nil),      // 16: tour.AbandonTourResponse
	(*CompleteTourRequest)(nil),      // 17: tour.CompleteTourRequest
	(*CompleteTourResponse)(nil),     // 18: tour.CompleteTourResponse
	(*GetTourExecutionRequest)(nil),  // 19: tour.GetTourExecutionRequest
	(*GetTourExecutionResponse)(nil), // 20: tour.GetTourExecutionResponse
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_tour_proto_depIdxs = []int32{
	21, // 0: tour.Tour.published_date_time:type_name -> google.protobuf.Timestamp
	21, // 1: tour.Tour.archived_date_time:type_name -> google.protobuf.Timestamp
	1,  // 2: tour.CreateTourResponse.tour:type_name -> tour.Tour
	1,  // 3: tour.GetAllToursByIdResponse.tours:type_name -> tour.Tour
	1,  // 4: tour.GetAllToursResponse.tours:type_name -> tour.Tour
	1,  // 5: tour.GetTourByIdResponse.tour:type_name -> tour.Tour
	1,  // 6: tour.UpdateTourRequest.tour:type_name -> tour.Tour
	1,  // 7: tour.UpdateTourResponse.tour:type_name -> tour.Tour
	21, // 8: tour.TourExecution.start_time:type_name -> google.protobuf.Timestamp
	21, // 9: tour.TourExecution.last_activity:type_name -> google.protobuf.Timestamp
	21, // 10: tour.TourExecution.completion_time:type_name -> google.protobuf.Timestamp
	12, // 11: tour.StartTourResponse.tour_execution:type_name -> tour.TourExecution
	12, // 12: tour.AbandonTourResponse.tour_execution:type_name -> tour.TourExecution
	12, // 13: tour.CompleteTourResponse.tour_execution:type_name -> tour.TourExecution
	12, // 14: tour.GetTourExecutionResponse.tour_execution:type_name -> tour.TourExecution
	1,  // 15: tour.GetTourExecutionResponse.tour:type_name -> tour.Tour
	2,  // 16: tour.TourGrpcService.CreateTour:input_type -> tour.CreateTourRequest
	4,  // 17: tour.TourGrpcService.GetAllToursById:input_type -> tour.GetAllToursByIdRequest
	6,  // 18: tour.TourGrpcService.GetAllTours:input_type -> tour.GetAllToursRequest
	8,  // 19: tour.TourGrpcService.GetTourById:input_type -> tour.GetTourByIdRequest
	10, // 20: tour.TourGrpcService.UpdateTour:input_type -> tour.UpdateTourRequest
	13, // 21: tour.TourGrpcService.StartTour:input_type -> tour.StartTourRequest
	15, // 22: tour.TourGrpcService.AbandonTour:input_type -> tour.AbandonTourRequest
	17, // 23: tour.TourGrpcService.CompleteTour:input_type -> tour.CompleteTourRequest
	19, // 24: tour.TourGrpcService.GetTourExecution:input_type -> tour.GetTourExecutionRequest
	3,  // 25: tour.TourGrpcService.CreateTour:output_type -> tour.CreateTourResponse
	5,  // 26: tour.TourGrpcService.GetAllToursById:output_type -> tour.GetAllToursByIdResponse
	7,  // 27: tour.TourGrpcService.GetAllTours:output_type -> tour.GetAllToursResponse
	9,  // 28: tour.TourGrpcService.GetTourById:output_type -> tour.GetTourByIdResponse
	11, // 29: tour.TourGrpcService.UpdateTour:output_type -> tour.UpdateTourResponse
	14, // 30: tour.TourGrpcService.StartTour:output_type -> tour.StartTourResponse
	16, // 31: tour.TourGrpcService.AbandonTour:output_type -> tour.AbandonTourResponse
	18, // 32: tour.TourGrpcService.CompleteTour:output_type -> tour.CompleteTourResponse
	20, // 33: tour.TourGrpcService.GetTourExecution:output_type -> tour.GetTourExecutionResponse
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_tour_proto_init() }
func file_tour_proto_init() {
	if File_tour_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tour_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Tour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateTourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllToursByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllToursByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllToursRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllToursResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetTourByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetTourByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*TourExecution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*StartTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*StartTourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*AbandonTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*AbandonTourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*CompleteTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*CompleteTourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetTourExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetTourExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tour_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_proto_goTypes,
		DependencyIndexes: file_tour_proto_depIdxs,
		EnumInfos:         file_tour_proto_enumTypes,
		MessageInfos:      file_tour_proto_msgTypes,
	}.Build()
	File_tour_proto = out.File
	file_tour_proto_rawDesc = nil
	file_tour_proto_goTypes = nil
	file_tour_proto_depIdxs = nil
}
