// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: tour.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId      string                 `protobuf:"bytes,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CreateTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourResponse) Reset() {
	*x = CreateTourResponse{}
	mi := &file_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourResponse) ProtoMessage() {}

func (x *CreateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourResponse.ProtoReflect.Descriptor instead.
func (*CreateTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type GetAllToursByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursByIdRequest) Reset() {
	*x = GetAllToursByIdRequest{}
	mi := &file_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursByIdRequest) ProtoMessage() {}

func (x *GetAllToursByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAllToursByIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllToursByIdRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type GetAllToursByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursByIdResponse) Reset() {
	*x = GetAllToursByIdResponse{}
	mi := &file_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursByIdResponse) ProtoMessage() {}

func (x *GetAllToursByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursByIdResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllToursByIdResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetAllToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursRequest) Reset() {
	*x = GetAllToursRequest{}
	mi := &file_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursRequest) ProtoMessage() {}

func (x *GetAllToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursRequest.ProtoReflect.Descriptor instead.
func (*GetAllToursRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{5}
}

type GetAllToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursResponse) Reset() {
	*x = GetAllToursResponse{}
	mi := &file_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursResponse) ProtoMessage() {}

func (x *GetAllToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllToursResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int32                  `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_tour_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{7}
}

func (x *GetTourByIdRequest) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type GetTourByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdResponse) Reset() {
	*x = GetTourByIdResponse{}
	mi := &file_tour_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdResponse) ProtoMessage() {}

func (x *GetTourByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTourByIdResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{8}
}

func (x *GetTourByIdResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

var File_tour_proto protoreflect.FileDescriptor

const file_tour_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tour.proto\x12\x04tour\"\xcb\x01\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\tR\bauthorId\"\x9a\x01\n" +
	"\x11CreateTourRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\"4\n" +
	"\x12CreateTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"5\n" +
	"\x16GetAllToursByIdRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\";\n" +
	"\x17GetAllToursByIdResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\"\x14\n" +
	"\x12GetAllToursRequest\"7\n" +
	"\x13GetAllToursResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\"-\n" +
	"\x12GetTourByIdRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\x05R\x06tourId\"5\n" +
	"\x13GetTourByIdResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour2\xaa\x02\n" +
	"\x0fTourGrpcService\x12?\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x18.tour.CreateTourResponse\x12N\n" +
	"\x0fGetAllToursById\x12\x1c.tour.GetAllToursByIdRequest\x1a\x1d.tour.GetAllToursByIdResponse\x12B\n" +
	"\vGetAllTours\x12\x18.tour.GetAllToursRequest\x1a\x19.tour.GetAllToursResponse\x12B\n" +
	"\vGetTourById\x12\x18.tour.GetTourByIdRequest\x1a\x19.tour.GetTourByIdResponseBX\n" +
	"\x15com.example.tour.grpcP\x01Z=github.com/pavlovicisidora/soa-team7/Backend/APIGateway/protob\x06proto3"

var (
	file_tour_proto_rawDescOnce sync.Once
	file_tour_proto_rawDescData []byte
)

func file_tour_proto_rawDescGZIP() []byte {
	file_tour_proto_rawDescOnce.Do(func() {
		file_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)))
	})
	return file_tour_proto_rawDescData
}

var file_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tour_proto_goTypes = []any{
	(*Tour)(nil),                    // 0: tour.Tour
	(*CreateTourRequest)(nil),       // 1: tour.CreateTourRequest
	(*CreateTourResponse)(nil),      // 2: tour.CreateTourResponse
	(*GetAllToursByIdRequest)(nil),  // 3: tour.GetAllToursByIdRequest
	(*GetAllToursByIdResponse)(nil), // 4: tour.GetAllToursByIdResponse
	(*GetAllToursRequest)(nil),      // 5: tour.GetAllToursRequest
	(*GetAllToursResponse)(nil),     // 6: tour.GetAllToursResponse
	(*GetTourByIdRequest)(nil),      // 7: tour.GetTourByIdRequest
	(*GetTourByIdResponse)(nil),     // 8: tour.GetTourByIdResponse
}
var file_tour_proto_depIdxs = []int32{
	0, // 0: tour.CreateTourResponse.tour:type_name -> tour.Tour
	0, // 1: tour.GetAllToursByIdResponse.tours:type_name -> tour.Tour
	0, // 2: tour.GetAllToursResponse.tours:type_name -> tour.Tour
	0, // 3: tour.GetTourByIdResponse.tour:type_name -> tour.Tour
	1, // 4: tour.TourGrpcService.CreateTour:input_type -> tour.CreateTourRequest
	3, // 5: tour.TourGrpcService.GetAllToursById:input_type -> tour.GetAllToursByIdRequest
	5, // 6: tour.TourGrpcService.GetAllTours:input_type -> tour.GetAllToursRequest
	7, // 7: tour.TourGrpcService.GetTourById:input_type -> tour.GetTourByIdRequest
	2, // 8: tour.TourGrpcService.CreateTour:output_type -> tour.CreateTourResponse
	4, // 9: tour.TourGrpcService.GetAllToursById:output_type -> tour.GetAllToursByIdResponse
	6, // 10: tour.TourGrpcService.GetAllTours:output_type -> tour.GetAllToursResponse
	8, // 11: tour.TourGrpcService.GetTourById:output_type -> tour.GetTourByIdResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tour_proto_init() }
func file_tour_proto_init() {
	if File_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_proto_goTypes,
		DependencyIndexes: file_tour_proto_depIdxs,
		MessageInfos:      file_tour_proto_msgTypes,
	}.Build()
	File_tour_proto = out.File
	file_tour_proto_goTypes = nil
	file_tour_proto_depIdxs = nil
}
