// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: stakeholders.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserPublicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPublicInfoRequest) Reset() {
	*x = GetUserPublicInfoRequest{}
	mi := &file_stakeholders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPublicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPublicInfoRequest) ProtoMessage() {}

func (x *GetUserPublicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPublicInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserPublicInfoRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserPublicInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPublicInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	ProfilePicUrl string                 `protobuf:"bytes,5,opt,name=profile_pic_url,json=profilePicUrl,proto3" json:"profile_pic_url,omitempty"` // Koristimo URL za sliku
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPublicInfoResponse) Reset() {
	*x = GetUserPublicInfoResponse{}
	mi := &file_stakeholders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPublicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPublicInfoResponse) ProtoMessage() {}

func (x *GetUserPublicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPublicInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserPublicInfoResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserPublicInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPublicInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserPublicInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserPublicInfoResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *GetUserPublicInfoResponse) GetProfilePicUrl() string {
	if x != nil {
		return x.ProfilePicUrl
	}
	return ""
}

var File_stakeholders_proto protoreflect.FileDescriptor

const file_stakeholders_proto_rawDesc = "" +
	"\n" +
	"\x12stakeholders.proto\x12\fstakeholders\"3\n" +
	"\x18GetUserPublicInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa6\x01\n" +
	"\x19GetUserPublicInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurname\x12&\n" +
	"\x0fprofile_pic_url\x18\x05 \x01(\tR\rprofilePicUrl2z\n" +
	"\x12StakeholderService\x12d\n" +
	"\x11GetUserPublicInfo\x12&.stakeholders.GetUserPublicInfoRequest\x1a'.stakeholders.GetUserPublicInfoResponseBu\n" +
	"\x1dcom.example.stakeholders.grpcB\x11StakeholdersProtoP\x01Z?github.com/pavlovicisidora/soa-team7/Backend/Stakeholders/protob\x06proto3"

var (
	file_stakeholders_proto_rawDescOnce sync.Once
	file_stakeholders_proto_rawDescData []byte
)

func file_stakeholders_proto_rawDescGZIP() []byte {
	file_stakeholders_proto_rawDescOnce.Do(func() {
		file_stakeholders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stakeholders_proto_rawDesc), len(file_stakeholders_proto_rawDesc)))
	})
	return file_stakeholders_proto_rawDescData
}

var file_stakeholders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stakeholders_proto_goTypes = []any{
	(*GetUserPublicInfoRequest)(nil),  // 0: stakeholders.GetUserPublicInfoRequest
	(*GetUserPublicInfoResponse)(nil), // 1: stakeholders.GetUserPublicInfoResponse
}
var file_stakeholders_proto_depIdxs = []int32{
	0, // 0: stakeholders.StakeholderService.GetUserPublicInfo:input_type -> stakeholders.GetUserPublicInfoRequest
	1, // 1: stakeholders.StakeholderService.GetUserPublicInfo:output_type -> stakeholders.GetUserPublicInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stakeholders_proto_init() }
func file_stakeholders_proto_init() {
	if File_stakeholders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stakeholders_proto_rawDesc), len(file_stakeholders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stakeholders_proto_goTypes,
		DependencyIndexes: file_stakeholders_proto_depIdxs,
		MessageInfos:      file_stakeholders_proto_msgTypes,
	}.Build()
	File_stakeholders_proto = out.File
	file_stakeholders_proto_goTypes = nil
	file_stakeholders_proto_depIdxs = nil
}
